name: ark
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.8
  - pip
  # Server
  - coverage<6.0
  - coverage-badge==1.1.0
  - flask==2.0.2
  - pillow==8.3.1
  - pydicom==2.2.2
  - requests==2.27.1
  - tqdm==4.62.3
  # Model
  - lifelines==0.24.15
  - scikit-image==0.18.2
  - scikit-learn==0.23.2
  - torchvision==0.10.0
  - pip:
      - torch==1.9.0
