name: ark
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.8
  - pip
  # Server
  - coverage<6.0
  - coverage-badge==1.1.0
  - flask==2.0.2
  - Pillow==8.3.2
  - pydicom==2.2.2
  - requests==2.27.1
  - tqdm==4.62.3
