name: ark
dependencies:
  - python=3.8
  - pip
  - pip:
    - coverage<6.0
    - coverage-badge
    - flask
    - pydicom
    - scikit-learn==0.23.1
    - torch==1.9.0
    - torchvision==0.2.0
    - scipy
    - numpy
    - Pillow
    - tqdm
    - mock
    - statsmodels
    - scikit-image
    - imageio
    - gitpython
    - lifelines
